#!/bin/sh
# postinst script for testapp-gui

set -e

# Обновление кэша иконок
if [ -x /usr/bin/update-icon-caches ]; then
    update-icon-caches /usr/share/pixmaps
fi

# Обновление кэша приложений
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q
fi

exit 0

